#pragma once

#include "Tfs1098SystemChannelRegistry.hpp"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fantasy::studio::runtime {

struct Tfs1098OtcExtendedBridgeArtifacts {
    std::string serverLua;
    std::string clientLua;
    std::string clientOtmod;
};

struct Tfs1098OtcExtendedBridgeWriteReport {
    bool success = false;
    std::vector<std::filesystem::path> generatedFiles;
    std::vector<std::string> errors;
};

class Tfs1098OtcExtendedBridge {
public:
    static constexpr const char* EnvelopePrefix = "FANTASY/";

    [[nodiscard]] static Tfs1098OtcExtendedBridgeArtifacts generate(
        std::vector<RuntimeChannelBinding> bindings) {

        Tfs1098SystemChannelRegistry::validate(bindings);
        return {
            generateServerLua(bindings),
            generateClientLua(bindings),
            generateClientOtmod(),
        };
    }

    [[nodiscard]] static Tfs1098OtcExtendedBridgeWriteReport write(
        const std::filesystem::path& runtimeDirectory,
        const std::filesystem::path& clientDirectory,
        const std::vector<RuntimeChannelBinding>& bindings) {

        Tfs1098OtcExtendedBridgeWriteReport report;
        try {
            if (runtimeDirectory.empty() || clientDirectory.empty()) {
                throw std::runtime_error("runtimeDirectory and clientDirectory are required");
            }
            const auto artifacts = generate(bindings);

            const auto serverScript = runtimeDirectory / "data" / "creaturescripts" / "scripts" / "extendedopcode.lua";
            const auto clientModuleDirectory = clientDirectory / "mods" / "fantasy_runtime_bridge";
            const auto clientLua = clientModuleDirectory / "fantasy_runtime_bridge.lua";
            const auto clientOtmod = clientModuleDirectory / "fantasy_runtime_bridge.otmod";

            writeText(serverScript, artifacts.serverLua);
            writeText(clientLua, artifacts.clientLua);
            writeText(clientOtmod, artifacts.clientOtmod);

            report.generatedFiles = {serverScript, clientLua, clientOtmod};
            report.success = true;
        } catch (const std::exception& error) {
            report.errors.emplace_back(error.what());
        }
        return report;
    }

private:
    [[nodiscard]] static std::string generateServerLua(
        const std::vector<RuntimeChannelBinding>& bindings) {

        std::ostringstream out;
        out
            << "-- Generated by Fantasy Studio. Do not assign numeric opcodes in authored systems.\n"
            << "-- This bridge targets vanilla TFS 1.4.2 and preserves upstream opcode 1 language behavior.\n\n"
            << "local OPCODE_LANGUAGE = 1\n"
            << "local FANTASY_PREFIX = '" << EnvelopePrefix << "'\n\n"
            << "local CHANNEL_BY_OPCODE = {\n";
        for (const auto& binding : bindings) {
            out << "  [" << binding.wireCode << "] = '" << binding.channel.value << "',\n";
        }
        out
            << "}\n\n"
            << "local OPCODE_BY_CHANNEL = {\n";
        for (const auto& binding : bindings) {
            out << "  ['" << binding.channel.value << "'] = " << binding.wireCode << ",\n";
        }
        out
            << "}\n\n"
            << "FantasyRuntimeBridge = FantasyRuntimeBridge or {}\n"
            << "FantasyRuntimeBridge.handlers = FantasyRuntimeBridge.handlers or {}\n\n"
            << "local function encode(version, payload)\n"
            << "  return FANTASY_PREFIX .. tostring(version or 1) .. '\\n' .. (payload or '')\n"
            << "end\n\n"
            << "local function decode(buffer)\n"
            << "  if buffer:sub(1, #FANTASY_PREFIX) ~= FANTASY_PREFIX then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  local separator = buffer:find('\\n', #FANTASY_PREFIX + 1, true)\n"
            << "  if not separator then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  local version = tonumber(buffer:sub(#FANTASY_PREFIX + 1, separator - 1))\n"
            << "  if not version or version < 1 then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  return version, buffer:sub(separator + 1)\n"
            << "end\n\n"
            << "function FantasyRuntimeBridge.register(channel, callback)\n"
            << "  if OPCODE_BY_CHANNEL[channel] == nil then\n"
            << "    error('Unknown Fantasy runtime channel: ' .. tostring(channel))\n"
            << "  end\n"
            << "  if type(callback) ~= 'function' then\n"
            << "    error('Fantasy runtime channel callback must be a function')\n"
            << "  end\n"
            << "  FantasyRuntimeBridge.handlers[channel] = callback\n"
            << "end\n\n"
            << "function FantasyRuntimeBridge.send(player, channel, payload, version)\n"
            << "  local opcode = OPCODE_BY_CHANNEL[channel]\n"
            << "  if opcode == nil then\n"
            << "    return false\n"
            << "  end\n"
            << "  return player:sendExtendedOpcode(opcode, encode(version, payload))\n"
            << "end\n\n"
            << "function onExtendedOpcode(player, opcode, buffer)\n"
            << "  if opcode == OPCODE_LANGUAGE then\n"
            << "    -- Preserve the vanilla TFS OTClient language example/contract.\n"
            << "    if buffer == 'en' or buffer == 'pt' then\n"
            << "      -- Projects may persist language preference in their own system.\n"
            << "    end\n"
            << "    return\n"
            << "  end\n\n"
            << "  local channel = CHANNEL_BY_OPCODE[opcode]\n"
            << "  if channel == nil then\n"
            << "    return\n"
            << "  end\n"
            << "  local version, payload = decode(buffer)\n"
            << "  if version == nil then\n"
            << "    return\n"
            << "  end\n"
            << "  local handler = FantasyRuntimeBridge.handlers[channel]\n"
            << "  if handler ~= nil then\n"
            << "    handler(player, payload, version)\n"
            << "  end\n"
            << "end\n";
        return out.str();
    }

    [[nodiscard]] static std::string generateClientLua(
        const std::vector<RuntimeChannelBinding>& bindings) {

        std::ostringstream out;
        out
            << "-- Generated by Fantasy Studio. Semantic channel names are the public contract.\n"
            << "local FANTASY_PREFIX = '" << EnvelopePrefix << "'\n\n"
            << "local CHANNEL_BY_OPCODE = {\n";
        for (const auto& binding : bindings) {
            out << "  [" << binding.wireCode << "] = '" << binding.channel.value << "',\n";
        }
        out
            << "}\n\n"
            << "local OPCODE_BY_CHANNEL = {\n";
        for (const auto& binding : bindings) {
            out << "  ['" << binding.channel.value << "'] = " << binding.wireCode << ",\n";
        }
        out
            << "}\n\n"
            << "FantasyRuntimeBridge = FantasyRuntimeBridge or {}\n"
            << "FantasyRuntimeBridge.handlers = FantasyRuntimeBridge.handlers or {}\n\n"
            << "local function encode(version, payload)\n"
            << "  return FANTASY_PREFIX .. tostring(version or 1) .. '\\n' .. (payload or '')\n"
            << "end\n\n"
            << "local function decode(buffer)\n"
            << "  if buffer:sub(1, #FANTASY_PREFIX) ~= FANTASY_PREFIX then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  local separator = buffer:find('\\n', #FANTASY_PREFIX + 1, true)\n"
            << "  if not separator then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  local version = tonumber(buffer:sub(#FANTASY_PREFIX + 1, separator - 1))\n"
            << "  if not version or version < 1 then\n"
            << "    return nil, nil\n"
            << "  end\n"
            << "  return version, buffer:sub(separator + 1)\n"
            << "end\n\n"
            << "local function onExtendedOpcode(protocol, opcode, buffer)\n"
            << "  local channel = CHANNEL_BY_OPCODE[opcode]\n"
            << "  if channel == nil then\n"
            << "    return\n"
            << "  end\n"
            << "  local version, payload = decode(buffer)\n"
            << "  if version == nil then\n"
            << "    return\n"
            << "  end\n"
            << "  local handler = FantasyRuntimeBridge.handlers[channel]\n"
            << "  if handler ~= nil then\n"
            << "    handler(payload, version, protocol)\n"
            << "  end\n"
            << "end\n\n"
            << "function FantasyRuntimeBridge.register(channel, callback)\n"
            << "  if OPCODE_BY_CHANNEL[channel] == nil then\n"
            << "    error('Unknown Fantasy runtime channel: ' .. tostring(channel))\n"
            << "  end\n"
            << "  if type(callback) ~= 'function' then\n"
            << "    error('Fantasy runtime channel callback must be a function')\n"
            << "  end\n"
            << "  FantasyRuntimeBridge.handlers[channel] = callback\n"
            << "end\n\n"
            << "function FantasyRuntimeBridge.send(channel, payload, version)\n"
            << "  local opcode = OPCODE_BY_CHANNEL[channel]\n"
            << "  local protocol = g_game.getProtocolGame()\n"
            << "  if opcode == nil or protocol == nil then\n"
            << "    return false\n"
            << "  end\n"
            << "  protocol:sendExtendedOpcode(opcode, encode(version, payload))\n"
            << "  return true\n"
            << "end\n\n"
            << "function init()\n";
        for (const auto& binding : bindings) {
            out << "  ProtocolGame.registerExtendedOpcode(" << binding.wireCode << ", onExtendedOpcode)\n";
        }
        out
            << "end\n\n"
            << "function terminate()\n";
        for (const auto& binding : bindings) {
            out << "  ProtocolGame.unregisterExtendedOpcode(" << binding.wireCode << ")\n";
        }
        out
            << "  FantasyRuntimeBridge.handlers = {}\n"
            << "end\n";
        return out.str();
    }

    [[nodiscard]] static std::string generateClientOtmod() {
        return
            "Module\n"
            "  name: fantasy_runtime_bridge\n"
            "  description: Fantasy semantic runtime channel bridge\n"
            "  author: Fantasy Studio\n"
            "  sandboxed: true\n"
            "  scripts: [ fantasy_runtime_bridge ]\n"
            "  @onLoad: init()\n"
            "  @onUnload: terminate()\n";
    }

    static void writeText(const std::filesystem::path& path, const std::string& text) {
        std::filesystem::create_directories(path.parent_path());
        std::ofstream output(path, std::ios::binary | std::ios::trunc);
        if (!output) {
            throw std::runtime_error("Unable to write Fantasy OTC extended bridge file: " + path.string());
        }
        output << text;
        if (!output) {
            throw std::runtime_error("Failed while writing Fantasy OTC extended bridge file: " + path.string());
        }
    }
};

} // namespace fantasy::studio::runtime
